# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TicDesign
owner:
  name: Mobvoi, Inc.
  link: http://www.mobvoi.com/
description: > # this means to ignore newlines until "baseurl:"
  专门为智能手表设计的UI开源库，针对智能手表的小屏幕提出了一整套UI解决方案。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ticdesign.chumenwenwen.com" # the base hostname & protocol for your site

github:
  name: GitHub
  link: https://github.com/mobvoi/ticdesign/

# folders
collections:
  doc:
    output: true
  design:
    output: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed
